trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

variables:
  windowsScaledPool: 'Windows2022-20211130'
  linuxVMImage: 'ubuntu-latest'

jobs:
- template: build/ci/.azure-devops-commitsar.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-pipeline-validations.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-docs.yml
  parameters:
    poolName: '$(windowsScaledPool)'
