trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*
      
  paths:
    exclude:
    - '/'
    include:
    - doc/*

variables:
  windows2022HostedVMImage: 'windows-2022'

jobs:
- template: build/ci/.azure-devops-docs.yml
  parameters:
    vmImage: '$(windows2022HostedVMImage)'
