trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

variables:
  windowsScaledPool: 'Windows2022-20230613'
  linuxVMImage: 'ubuntu-latest'

stages:
- template: build/ci/.azure-devops-stages-docs.yml
